[workspace]
members = [
    "addin-fixed-weights/program",
    "addin-fixed-weights/mainnet",
    "addin-vesting/program",
    "addin-vesting/cli",
    "governance-test-scripts",
    "governance-lib",
]
exclude = [
    "solana-program-library",
]
