[profile.release]
overflow-checks = true

[workspace]
members = [
    "addin-fixed-weights/program",
    "addin-fixed-weights/mainnet",
    "addin-vesting/program",
    "addin-vesting/cli",
    "maintenance/program",
]
exclude = [
    "solana-program-library",
]
