version: "2.1"

services:
  solana:
    container_name: solana
    image: solanalabs/solana:v1.9.12
    environment:
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
      - SOLANA_URL=http://127.0.0.1:8899
      - SOLANA_RUN_SH_VALIDATOR_ARGS=--gossip-host solana
    hostname: solana
    ports:
      - 8899:8899
      - 9900:9900
      - 8900:8900
      - 8003:8003/udp
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8003/udp"

networks:
  default:
    name: neon-governance-run-test-net
