steps:

  - label: ":docker: build docker image"
    command:
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":cop::skin-tone-2: deploy check"
    command:
      - ".buildkite/steps/deploy-tests.sh"
    timeout: 60

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "main ci-* v*.*.*"
